import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "fr" | "ar" | "es" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.users": "Users",
    "nav.courses": "Courses",
    "nav.enrollments": "Enrollments",
    "nav.exams": "Exams",
    "nav.jobOffers": "Job Offers",
    "nav.certificates": "Certificates",
    "nav.payments": "Payments",
    "nav.statistics": "Statistics",
    "nav.settings": "Settings",
    
    // Common
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.view": "View",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.name": "Name",
    "common.email": "Email",
    "common.password": "Password",
    "common.type": "Type",
    "common.created": "Created",
    "common.price": "Price",
    "common.free": "Free",
    "common.active": "Active",
    "common.completed": "Completed",
    "common.loading": "Loading",
    "common.success": "Success",
    "common.error": "Error",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.totalUsers": "Total Users",
    "dashboard.learners": "Learners",
    "dashboard.instructors": "Instructors",
    "dashboard.courses": "Courses",
    "dashboard.revenue": "Revenue",
    "dashboard.visitorStats": "Visitor Statistics",
    "dashboard.tasks": "Tasks",
    "dashboard.recentActivities": "Recent Activities",
    "dashboard.topCourses": "Top Courses",
    "dashboard.students": "students",
    "dashboard.thisMonth": "This month",
    
    // Users
    "users.title": "Users Management",
    "users.subtitle": "Manage and organize your users",
    "users.addUser": "Add User",
    "users.editUser": "Edit User",
    "users.deleteUser": "Delete User",
    "users.fullName": "Full Name",
    "users.emailAddress": "Email Address",
    "users.userType": "User Type",
    "users.searchPlaceholder": "Search users by name or email...",
    "users.filterByType": "Filter by type",
    "users.allTypes": "All Types",
    "users.learner": "Learner",
    "users.instructor": "Instructor",
    "users.admin": "Admin",
    "users.recruiter": "Recruiter",
    "users.totalUsers": "Total Users",
    "users.admins": "Admins",
    "users.addSuccess": "User added successfully!",
    "users.updateSuccess": "User updated successfully!",
    "users.deleteSuccess": "User deleted successfully!",
    "users.fillAllFields": "Please fill all fields",
    "users.deleteConfirm": "Are you sure?",
    "users.deleteMessage": "This action cannot be undone. This will permanently delete the user account and remove their data from our servers.",
    
    // Courses
    "courses.title": "Courses Management",
    "courses.subtitle": "Create and manage your courses",
    "courses.addCourse": "Add Course",
    "courses.editCourse": "Edit Course",
    "courses.deleteCourse": "Delete Course",
    "courses.viewCourse": "Course Details",
    "courses.courseName": "Course Name",
    "courses.instructorName": "Instructor Name",
    "courses.courseType": "Course Type",
    "courses.description": "Description",
    "courses.courseFiles": "Course Files",
    "courses.searchPlaceholder": "Search courses by name or instructor...",
    "courses.filterByType": "Filter by type",
    "courses.allTypes": "All Types",
    "courses.totalCourses": "Total Courses",
    "courses.totalStudents": "Total Students",
    "courses.totalRevenue": "Total Revenue",
    "courses.avgRating": "Avg. Rating",
    "courses.rating": "Rating",
    "courses.addSuccess": "Course added successfully!",
    "courses.updateSuccess": "Course updated successfully!",
    "courses.deleteSuccess": "Course deleted successfully!",
    "courses.fillRequired": "Please fill all required fields",
    "courses.deleteConfirm": "Are you sure?",
    "courses.deleteMessage": "This action cannot be undone. This will permanently delete the course and all associated data.",
    "courses.uploadPrompt": "Click to upload or drag and drop",
    "courses.uploadHint": "PDF, MP4, PPTX, DOC (max. 100MB)",
    
    // Enrollments
    "enrollments.title": "Enrollments Management",
    "enrollments.subtitle": "Track and manage student enrollments",
    "enrollments.totalEnrollments": "Total Enrollments",
    "enrollments.inProgress": "In Progress",
    "enrollments.student": "Student",
    "enrollments.courseName": "Course Name",
    "enrollments.progress": "Progress",
    "enrollments.payment": "Payment",
    "enrollments.enrollmentDate": "Enrollment Date",
    "enrollments.completionDate": "Completion Date",
    "enrollments.paymentStatus": "Payment Status",
    "enrollments.courseProgress": "Course Progress",
    "enrollments.finalGrade": "Final Grade",
    "enrollments.viewDetails": "View complete enrollment information",
    "enrollments.searchPlaceholder": "Search enrollments...",
    "enrollments.filterByStatus": "Filter by status",
    "enrollments.allStatus": "All Status",
    "enrollments.deleteSuccess": "Enrollment deleted successfully!",
    "enrollments.exportSuccess": "Exporting enrollments data...",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.viewAll": "View all notifications",
    "notifications.newUser": "New user registered",
    "notifications.courseCompleted": "Course completed",
    "notifications.paymentReceived": "Payment received",
    "notifications.newEnrollment": "New enrollment",
    
    // User Menu
    "userMenu.myAccount": "My Account",
    "userMenu.profile": "Profile",
    "userMenu.settings": "Settings",
    "userMenu.logout": "Log out",
    
    // Footer
    "footer.copyright": "© 2026 Formanova",
    
    // Exams
    "exams.title": "Exams Management",
    "exams.totalExams": "Total Exams",
    "exams.upcomingExams": "Upcoming Exams",
    "exams.activeExams": "Active Exams",
    "exams.passedExams": "Passed Exams",
    "exams.examTitle": "Exam Title",
    "exams.course": "Course",
    "exams.dueDate": "Due Date",
    "exams.totalQuestions": "Total Questions",
    "exams.attempts": "Attempts",
    "exams.passRate": "Pass Rate",
    "exams.upcoming": "Upcoming",
    "exams.active": "Active",
    "exams.searchPlaceholder": "Search Exams...",
    "exams.sortByType": "Sort By Type",
    
    // Job Offers
    "jobs.title": "Job Offers Management",
    "jobs.totalJobOffers": "Total Job Offers",
    "jobs.openPositions": "Open Positions",
    "jobs.closedPositions": "Closed Positions",
    "jobs.companies": "Companies",
    "jobs.jobPosition": "Job Position",
    "jobs.company": "Company",
    "jobs.postedDate": "Posted Date",
    "jobs.applicationDeadline": "Application Deadline",
    "jobs.open": "Open",
    "jobs.closed": "Closed",
    "jobs.searchPlaceholder": "Search Job Offers...",
    
    // Certificates
    "certificates.title": "Certificates Management",
    "certificates.addCertificate": "+ Add Certificate",
    "certificates.totalCertificates": "Total Certificates",
    "certificates.issuedCertificates": "Issued Certificates",
    "certificates.verifiedCertificates": "Verified Certificates",
    "certificates.pendingCertificates": "Pending Certificates",
    "certificates.issueDate": "Issue Date",
    "certificates.verificationCode": "Verification Code",
    "certificates.issued": "Issued",
    "certificates.pending": "Pending",
    "certificates.searchPlaceholder": "Search Certificates...",
    
    // Payment
    "payment.title": "Payment Management",
    "payment.totalRevenue": "Total Revenue",
    "payment.completedPayments": "Completed Payments",
    "payment.pendingPayments": "Pending Payments",
    "payment.refunds": "Refunds",
    "payment.method": "Method",
    "payment.failed": "Failed",
    "payment.tasks": "Tasks",
    "payment.showThisMonth": "Show: This month",
    "payment.failedPayments": "Failed Payments",
    "payment.searchPlaceholder": "Search Payments...",
    
    // Statistics
    "stats.title": "Statistics",
    "stats.totalUsers": "Total Users",
    "stats.totalCourses": "Total Courses",
    "stats.totalEnrollments": "Total Enrollments",
    "stats.certificatesIssued": "Certificates Issued",
    "stats.userGrowth": "User Growth",
    "stats.monthly": "Monthly",
    "stats.enrollmentsOverview": "Enrollments Overview",
    
    // Settings
    "settings.title": "Settings",
    "settings.searchPlaceholder": "Search Settings...",
    "settings.general": "General",
    "settings.systemLanguage": "System Language",
    "settings.userSignUp": "User Sign up",
    "settings.allowSignUp": "Allow new users to sign up",
    "settings.adminTheme": "Admin Dashboard Theme",
    "settings.defaultUserTheme": "Default Theme for Users",
    "settings.lightTheme": "Light Theme",
    "settings.darkTheme": "Dark Theme",
    "settings.autoTheme": "Auto",
    "settings.timeZone": "Time Zone",
    "settings.dateTimeFormat": "Date and Time Format",
    "settings.currency": "Currency",
    "settings.notifications": "Notifications",
    "settings.allowNotifications": "Allow system notifications",
    "settings.systemUpdateFreq": "System Update Frequency",
    "settings.securityChecksFreq": "Security Checks Frequency",
    "settings.saveChanges": "Save Changes",
    "settings.weekly": "Weekly",
    "settings.monthly": "Monthly",
    "settings.daily": "Daily",
    
    // Pagination
    "pagination.showing": "Showing",
    "pagination.to": "to",
    "pagination.of": "of",
    "pagination.entries": "entries",
  },
  fr: {
    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.users": "Utilisateurs",
    "nav.courses": "Cours",
    "nav.enrollments": "Inscriptions",
    "nav.exams": "Examens",
    "nav.jobOffers": "Offres d'emploi",
    "nav.certificates": "Certificats",
    "nav.payments": "Paiements",
    "nav.statistics": "Statistiques",
    "nav.settings": "Paramètres",
    
    // Common
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.export": "Exporter",
    "common.add": "Ajouter",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.close": "Fermer",
    "common.view": "Voir",
    "common.actions": "Actions",
    "common.status": "Statut",
    "common.name": "Nom",
    "common.email": "Email",
    "common.password": "Mot de passe",
    "common.type": "Type",
    "common.created": "Créé",
    "common.price": "Prix",
    "common.free": "Gratuit",
    "common.active": "Actif",
    "common.completed": "Terminé",
    "common.loading": "Chargement",
    "common.success": "Succès",
    "common.error": "Erreur",
    
    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.totalUsers": "Total Utilisateurs",
    "dashboard.learners": "Apprenants",
    "dashboard.instructors": "Instructeurs",
    "dashboard.courses": "Cours",
    "dashboard.revenue": "Revenu",
    "dashboard.visitorStats": "Statistiques des visiteurs",
    "dashboard.tasks": "Tâches",
    "dashboard.recentActivities": "Activités récentes",
    "dashboard.topCourses": "Meilleurs cours",
    "dashboard.students": "étudiants",
    "dashboard.thisMonth": "Ce mois",
    
    // Users
    "users.title": "Gestion des utilisateurs",
    "users.subtitle": "Gérer et organiser vos utilisateurs",
    "users.addUser": "Ajouter un utilisateur",
    "users.editUser": "Modifier l'utilisateur",
    "users.deleteUser": "Supprimer l'utilisateur",
    "users.fullName": "Nom complet",
    "users.emailAddress": "Adresse e-mail",
    "users.userType": "Type d'utilisateur",
    "users.searchPlaceholder": "Rechercher par nom ou email...",
    "users.filterByType": "Filtrer par type",
    "users.allTypes": "Tous les types",
    "users.learner": "Apprenant",
    "users.instructor": "Instructeur",
    "users.admin": "Administrateur",
    "users.recruiter": "Recruteur",
    "users.totalUsers": "Total Utilisateurs",
    "users.admins": "Administrateurs",
    "users.addSuccess": "Utilisateur ajouté avec succès!",
    "users.updateSuccess": "Utilisateur mis à jour avec succès!",
    "users.deleteSuccess": "Utilisateur supprimé avec succès!",
    "users.fillAllFields": "Veuillez remplir tous les champs",
    "users.deleteConfirm": "Êtes-vous sûr?",
    "users.deleteMessage": "Cette action est irréversible. Cela supprimera définitivement le compte utilisateur.",
    
    // Courses
    "courses.title": "Gestion des cours",
    "courses.subtitle": "Créer et gérer vos cours",
    "courses.addCourse": "Ajouter un cours",
    "courses.editCourse": "Modifier le cours",
    "courses.deleteCourse": "Supprimer le cours",
    "courses.viewCourse": "Détails du cours",
    "courses.courseName": "Nom du cours",
    "courses.instructorName": "Nom de l'instructeur",
    "courses.courseType": "Type de cours",
    "courses.description": "Description",
    "courses.courseFiles": "Fichiers du cours",
    "courses.searchPlaceholder": "Rechercher par nom ou instructeur...",
    "courses.filterByType": "Filtrer par type",
    "courses.allTypes": "Tous les types",
    "courses.totalCourses": "Total Cours",
    "courses.totalStudents": "Total Étudiants",
    "courses.totalRevenue": "Revenu Total",
    "courses.avgRating": "Note Moyenne",
    "courses.rating": "Note",
    "courses.addSuccess": "Cours ajouté avec succès!",
    "courses.updateSuccess": "Cours mis à jour avec succès!",
    "courses.deleteSuccess": "Cours supprimé avec succès!",
    "courses.fillRequired": "Veuillez remplir tous les champs requis",
    "courses.deleteConfirm": "Êtes-vous sûr?",
    "courses.deleteMessage": "Cette action supprimera définitivement le cours et toutes les données associées.",
    "courses.uploadPrompt": "Cliquez pour télécharger ou glissez-déposez",
    "courses.uploadHint": "PDF, MP4, PPTX, DOC (max. 100MB)",
    
    // Enrollments
    "enrollments.title": "Gestion des inscriptions",
    "enrollments.subtitle": "Suivre et gérer les inscriptions des étudiants",
    "enrollments.totalEnrollments": "Total Inscriptions",
    "enrollments.inProgress": "En cours",
    "enrollments.student": "Étudiant",
    "enrollments.courseName": "Nom du cours",
    "enrollments.progress": "Progrès",
    "enrollments.payment": "Paiement",
    "enrollments.enrollmentDate": "Date d'inscription",
    "enrollments.completionDate": "Date d'achèvement",
    "enrollments.paymentStatus": "Statut du paiement",
    "enrollments.courseProgress": "Progrès du cours",
    "enrollments.finalGrade": "Note finale",
    "enrollments.viewDetails": "Voir les informations complètes d'inscription",
    "enrollments.searchPlaceholder": "Rechercher des inscriptions...",
    "enrollments.filterByStatus": "Filtrer par statut",
    "enrollments.allStatus": "Tous les statuts",
    "enrollments.deleteSuccess": "Inscription supprimée avec succès!",
    "enrollments.exportSuccess": "Export des données d'inscription...",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Tout marquer comme lu",
    "notifications.viewAll": "Voir toutes les notifications",
    "notifications.newUser": "Nouvel utilisateur enregistré",
    "notifications.courseCompleted": "Cours terminé",
    "notifications.paymentReceived": "Paiement reçu",
    "notifications.newEnrollment": "Nouvelle inscription",
    
    // User Menu
    "userMenu.myAccount": "Mon compte",
    "userMenu.profile": "Profil",
    "userMenu.settings": "Paramètres",
    "userMenu.logout": "Se déconnecter",
    
    // Footer
    "footer.copyright": "© 2026 Formanova",
    
    // Exams
    "exams.title": "Gestion des examens",
    "exams.totalExams": "Total des examens",
    "exams.upcomingExams": "Examens à venir",
    "exams.activeExams": "Examens actifs",
    "exams.passedExams": "Examens réussis",
    "exams.examTitle": "Titre de l'examen",
    "exams.course": "Cours",
    "exams.dueDate": "Date limite",
    "exams.totalQuestions": "Total des questions",
    "exams.attempts": "Tentatives",
    "exams.passRate": "Taux de réussite",
    "exams.upcoming": "À venir",
    "exams.active": "Actif",
    "exams.searchPlaceholder": "Rechercher des examens...",
    "exams.sortByType": "Trier par type",
    
    // Job Offers
    "jobs.title": "Gestion des offres d'emploi",
    "jobs.totalJobOffers": "Total des offres d'emploi",
    "jobs.openPositions": "Postes vacants",
    "jobs.closedPositions": "Postes fermés",
    "jobs.companies": "Entreprises",
    "jobs.jobPosition": "Poste d'emploi",
    "jobs.company": "Entreprise",
    "jobs.postedDate": "Date de publication",
    "jobs.applicationDeadline": "Date limite de candidature",
    "jobs.open": "Ouvert",
    "jobs.closed": "Fermé",
    "jobs.searchPlaceholder": "Rechercher des offres d'emploi...",
    
    // Certificates
    "certificates.title": "Gestion des certificats",
    "certificates.addCertificate": "+ Ajouter un certificat",
    "certificates.totalCertificates": "Total des certificats",
    "certificates.issuedCertificates": "Certificats émis",
    "certificates.verifiedCertificates": "Certificats vérifiés",
    "certificates.pendingCertificates": "Certificats en attente",
    "certificates.issueDate": "Date d'émission",
    "certificates.verificationCode": "Code de vérification",
    "certificates.issued": "Émis",
    "certificates.pending": "En attente",
    "certificates.searchPlaceholder": "Rechercher des certificats...",
    
    // Payment
    "payment.title": "Gestion des paiements",
    "payment.totalRevenue": "Revenu total",
    "payment.completedPayments": "Paiements terminés",
    "payment.pendingPayments": "Paiements en attente",
    "payment.refunds": "Remboursements",
    "payment.method": "Méthode",
    "payment.failed": "Échoué",
    "payment.tasks": "Tâches",
    "payment.showThisMonth": "Afficher : Ce mois",
    "payment.failedPayments": "Paiements échoués",
    "payment.searchPlaceholder": "Rechercher des paiements...",
    
    // Statistics
    "stats.title": "Statistiques",
    "stats.totalUsers": "Total des utilisateurs",
    "stats.totalCourses": "Total des cours",
    "stats.totalEnrollments": "Total des inscriptions",
    "stats.certificatesIssued": "Certificats émis",
    "stats.userGrowth": "Croissance des utilisateurs",
    "stats.monthly": "Mensuel",
    "stats.enrollmentsOverview": "Aperçu des inscriptions",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.searchPlaceholder": "Rechercher des paramètres...",
    "settings.general": "Général",
    "settings.systemLanguage": "Langue du système",
    "settings.userSignUp": "Inscription des utilisateurs",
    "settings.allowSignUp": "Autoriser les nouveaux utilisateurs à s'inscrire",
    "settings.adminTheme": "Thème du tableau de bord administrateur",
    "settings.defaultUserTheme": "Thème par défaut pour les utilisateurs",
    "settings.lightTheme": "Thème clair",
    "settings.darkTheme": "Thème sombre",
    "settings.autoTheme": "Auto",
    "settings.timeZone": "Fuseau horaire",
    "settings.dateTimeFormat": "Format de date et d'heure",
    "settings.currency": "Devise",
    "settings.notifications": "Notifications",
    "settings.allowNotifications": "Autoriser les notifications système",
    "settings.systemUpdateFreq": "Fréquence de mise à jour du système",
    "settings.securityChecksFreq": "Fréquence des vérifications de sécurité",
    "settings.saveChanges": "Enregistrer les modifications",
    "settings.weekly": "Hebdomadaire",
    "settings.monthly": "Mensuel",
    "settings.daily": "Journalier",
    
    // Pagination
    "pagination.showing": "Affichage",
    "pagination.to": "à",
    "pagination.of": "sur",
    "pagination.entries": "entrées",
  },
  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.users": "المستخدمين",
    "nav.courses": "الدورات",
    "nav.enrollments": "التسجيلات",
    "nav.exams": "الامتحانات",
    "nav.jobOffers": "عروض العمل",
    "nav.certificates": "الشهادات",
    "nav.payments": "المدفوعات",
    "nav.statistics": "الإحصائيات",
    "nav.settings": "الإعدادات",
    
    // Common
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.export": "تصدير",
    "common.add": "إضافة",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.close": "إغلاق",
    "common.view": "عرض",
    "common.actions": "الإجراءات",
    "common.status": "الحالة",
    "common.name": "الاسم",
    "common.email": "البريد الإلكتروني",
    "common.password": "كلمة المرور",
    "common.type": "النوع",
    "common.created": "تاريخ الإنشاء",
    "common.price": "السعر",
    "common.free": "مجاني",
    "common.active": "نشط",
    "common.completed": "مكتمل",
    "common.loading": "جاري التحميل",
    "common.success": "نجح",
    "common.error": "خطأ",
    
    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.totalUsers": "إجمالي المستخدمين",
    "dashboard.learners": "المتعلمين",
    "dashboard.instructors": "المدربين",
    "dashboard.courses": "الدورات",
    "dashboard.revenue": "الإيرادات",
    "dashboard.visitorStats": "إحصائيات الزوار",
    "dashboard.tasks": "المهام",
    "dashboard.recentActivities": "الأنشطة الأخيرة",
    "dashboard.topCourses": "أفضل الدورات",
    "dashboard.students": "طلاب",
    "dashboard.thisMonth": "هذا الشهر",
    
    // Users
    "users.title": "إدارة المستخدمين",
    "users.subtitle": "إدارة وتنظيم المستخدمين",
    "users.addUser": "إضافة مستخدم",
    "users.editUser": "تعديل المستخدم",
    "users.deleteUser": "حذف المستخدم",
    "users.fullName": "الاسم الكامل",
    "users.emailAddress": "عنوان البريد الإلكتروني",
    "users.userType": "نوع المستخدم",
    "users.searchPlaceholder": "البحث بالاسم أو البريد الإلكتروني...",
    "users.filterByType": "تصف��ة حسب النوع",
    "users.allTypes": "كل الأنواع",
    "users.learner": "متعلم",
    "users.instructor": "مدرب",
    "users.admin": "مسؤول",
    "users.recruiter": "موظف توظيف",
    "users.totalUsers": "إجمالي المستخدمين",
    "users.admins": "المسؤولين",
    "users.addSuccess": "تمت إضافة المستخدم بنجاح!",
    "users.updateSuccess": "تم تحديث المستخدم بنجاح!",
    "users.deleteSuccess": "تم حذف المستخدم بنجاح!",
    "users.fillAllFields": "يرجى ملء جميع الحقول",
    "users.deleteConfirm": "هل أنت متأكد؟",
    "users.deleteMessage": "لا يمكن التراجع عن هذا الإجراء. سيؤدي ذلك إلى حذف حساب المستخدم نهائياً.",
    
    // Courses
    "courses.title": "إدارة الدورات",
    "courses.subtitle": "إنشاء وإدارة الدورات الخاصة بك",
    "courses.addCourse": "إضافة دورة",
    "courses.editCourse": "تعديل الدورة",
    "courses.deleteCourse": "حذف الدورة",
    "courses.viewCourse": "تفاصيل الدورة",
    "courses.courseName": "اسم الدورة",
    "courses.instructorName": "اسم المدرب",
    "courses.courseType": "نوع الدورة",
    "courses.description": "الوصف",
    "courses.courseFiles": "ملفات الدورة",
    "courses.searchPlaceholder": "البحث بالاسم أو المدرب...",
    "courses.filterByType": "تصفية حسب النوع",
    "courses.allTypes": "كل الأنواع",
    "courses.totalCourses": "إجمالي الدورات",
    "courses.totalStudents": "إجمالي الطلاب",
    "courses.totalRevenue": "إجمالي الإيرادات",
    "courses.avgRating": "متوسط التقييم",
    "courses.rating": "التقييم",
    "courses.addSuccess": "تمت إضافة الدورة بنجاح!",
    "courses.updateSuccess": "تم تحديث الدورة بنجاح!",
    "courses.deleteSuccess": "تم حذف الدورة بنجاح!",
    "courses.fillRequired": "يرجى ملء جميع الحقول المطلوبة",
    "courses.deleteConfirm": "هل أنت متأكد؟",
    "courses.deleteMessage": "سيؤدي ذلك إلى حذف الدورة وجميع البيانات المرتبطة بها نهائياً.",
    "courses.uploadPrompt": "انقر للتحميل أو اسحب وأفلت",
    "courses.uploadHint": "PDF, MP4, PPTX, DOC (الحد الأقصى 100 ميجابايت)",
    
    // Enrollments
    "enrollments.title": "إدارة التسجيلات",
    "enrollments.subtitle": "تتبع وإدارة تسجيلات الطلاب",
    "enrollments.totalEnrollments": "إجمالي التسجيلات",
    "enrollments.inProgress": "قيد التنفيذ",
    "enrollments.student": "الطالب",
    "enrollments.courseName": "اسم الدورة",
    "enrollments.progress": "التقدم",
    "enrollments.payment": "الدفع",
    "enrollments.enrollmentDate": "تاريخ التسجيل",
    "enrollments.completionDate": "تاريخ الإكمال",
    "enrollments.paymentStatus": "حالة الدفع",
    "enrollments.courseProgress": "تقدم الدورة",
    "enrollments.finalGrade": "الدرجة النهائية",
    "enrollments.viewDetails": "عرض معلومات التسجيل الكاملة",
    "enrollments.searchPlaceholder": "البحث عن التسجيلات...",
    "enrollments.filterByStatus": "تصفية حسب الحالة",
    "enrollments.allStatus": "كل الحالات",
    "enrollments.deleteSuccess": "تم حذف التسجيل بنجاح!",
    "enrollments.exportSuccess": "جاري تصدير بيانات التسجيل...",
    
    // Notifications
    "notifications.title": "الإشعارات",
    "notifications.markAllRead": "وضع علامة مقروء على الكل",
    "notifications.viewAll": "عرض جميع الإشعارات",
    "notifications.newUser": "مستخدم جديد مسجل",
    "notifications.courseCompleted": "الدورة مكتملة",
    "notifications.paymentReceived": "تم استلام الدفع",
    "notifications.newEnrollment": "تسجيل جديد",
    
    // User Menu
    "userMenu.myAccount": "حسابي",
    "userMenu.profile": "الملف الشخصي",
    "userMenu.settings": "الإعدادات",
    "userMenu.logout": "تسجيل الخروج",
    
    // Footer
    "footer.copyright": "© 2026 Formanova",
    
    // Exams
    "exams.title": "إدارة الامتحانات",
    "exams.totalExams": "إجمالي الامتحانات",
    "exams.upcomingExams": "الامتحانات القادمة",
    "exams.activeExams": "الامتحانات النشطة",
    "exams.passedExams": "الامتحانات المنجزة",
    "exams.examTitle": "عنوان الامتحان",
    "exams.course": "الدورة",
    "exams.dueDate": "تاريخ الاستحقاق",
    "exams.totalQuestions": "إجمالي الأسئلة",
    "exams.attempts": "محاولات",
    "exams.passRate": "معدل النجاح",
    "exams.upcoming": "قادم",
    "exams.active": "نشط",
    "exams.searchPlaceholder": "بحث عن الامتحانات...",
    "exams.sortByType": "فرز حسب النوع",
    
    // Job Offers
    "jobs.title": "إدارة عروض العمل",
    "jobs.totalJobOffers": "إجمالي عروض العمل",
    "jobs.openPositions": "الوظائف المفتوحة",
    "jobs.closedPositions": "الوظائف المغلقة",
    "jobs.companies": "الشركات",
    "jobs.jobPosition": "منصب العمل",
    "jobs.company": "الشركة",
    "jobs.postedDate": "تاريخ النشر",
    "jobs.applicationDeadline": "تاريخ انتهاء التقديم",
    "jobs.open": "مفتوح",
    "jobs.closed": "مغلق",
    "jobs.searchPlaceholder": "بحث عن عروض العمل...",
    
    // Certificates
    "certificates.title": "إدارة الشهادات",
    "certificates.addCertificate": "+ إضافة شهادة",
    "certificates.totalCertificates": "إجمالي الشهادات",
    "certificates.issuedCertificates": "الشهادات المصدرة",
    "certificates.verifiedCertificates": "الشهادات الموثقة",
    "certificates.pendingCertificates": "الشهادات المعلقة",
    "certificates.issueDate": "تاريخ الإصدار",
    "certificates.verificationCode": "رمز التحقق",
    "certificates.issued": "صدرت",
    "certificates.pending": "معلقة",
    "certificates.searchPlaceholder": "بحث عن الشهادات...",
    
    // Payment
    "payment.title": "إدارة الدفعات",
    "payment.totalRevenue": "إجمالي الإيرادات",
    "payment.completedPayments": "الدفعات المكتملة",
    "payment.pendingPayments": "الدفعات المعلقة",
    "payment.refunds": "المبالغ المستردة",
    "payment.method": "الطريقة",
    "payment.failed": "فشل",
    "payment.tasks": "المهام",
    "payment.showThisMonth": "عرض: هذا الشهر",
    "payment.failedPayments": "الدفعات الفاشلة",
    "payment.searchPlaceholder": "بحث عن الدفعات...",
    
    // Statistics
    "stats.title": "الإحصائيات",
    "stats.totalUsers": "إجمالي المستخدمين",
    "stats.totalCourses": "إجمالي الدورات",
    "stats.totalEnrollments": "إجمالي التسجيلات",
    "stats.certificatesIssued": "الشهادات المصدرة",
    "stats.userGrowth": "نمو المستخدمين",
    "stats.monthly": "شهري",
    "stats.enrollmentsOverview": "نظرة عامة على التسجيلات",
    
    // Settings
    "settings.title": "الإعدادات",
    "settings.searchPlaceholder": "بحث عن الإعدادات...",
    "settings.general": "عام",
    "settings.systemLanguage": "لغة النظام",
    "settings.userSignUp": "تسجيل المستخدمين",
    "settings.allowSignUp": "السماح للمستخدمين الجدد بالتسجيل",
    "settings.adminTheme": "موضوع لوحة التحكم للمسؤول",
    "settings.defaultUserTheme": "موضوع افتراضي للمستخدمين",
    "settings.lightTheme": "موضوع فاتح",
    "settings.darkTheme": "موضوع داكن",
    "settings.autoTheme": "تلقائي",
    "settings.timeZone": "منطقة زمنية",
    "settings.dateTimeFormat": "تنسيق التاريخ والوقت",
    "settings.currency": "عملة",
    "settings.notifications": "الإشعارات",
    "settings.allowNotifications": "السماح بإشعارات النظام",
    "settings.systemUpdateFreq": "تردد تحديث النظام",
    "settings.securityChecksFreq": "تردد فحوصات الأمان",
    "settings.saveChanges": "حفظ التغييرات",
    "settings.weekly": "أسبوعي",
    "settings.monthly": "شهري",
    "settings.daily": "يومي",
    
    // Pagination
    "pagination.showing": "عرض",
    "pagination.to": "إلى",
    "pagination.of": "من",
    "pagination.entries": "سجلات",
  },
  es: {
    // Navigation
    "nav.dashboard": "Panel",
    "nav.users": "Usuarios",
    "nav.courses": "Cursos",
    "nav.enrollments": "Inscripciones",
    "nav.exams": "Exámenes",
    "nav.jobOffers": "Ofertas de trabajo",
    "nav.certificates": "Certificados",
    "nav.payments": "Pagos",
    "nav.statistics": "Estadísticas",
    "nav.settings": "Configuración",
    
    // Common
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.export": "Exportar",
    "common.add": "Agregar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.close": "Cerrar",
    "common.view": "Ver",
    "common.actions": "Acciones",
    "common.status": "Estado",
    "common.name": "Nombre",
    "common.email": "Correo",
    "common.password": "Contraseña",
    "common.type": "Tipo",
    "common.created": "Creado",
    "common.price": "Precio",
    "common.free": "Gratis",
    "common.active": "Activo",
    "common.completed": "Completado",
    "common.loading": "Cargando",
    "common.success": "Éxito",
    "common.error": "Error",
    
    // Dashboard
    "dashboard.title": "Panel de Control",
    "dashboard.totalUsers": "Total Usuarios",
    "dashboard.learners": "Estudiantes",
    "dashboard.instructors": "Instructores",
    "dashboard.courses": "Cursos",
    "dashboard.revenue": "Ingresos",
    "dashboard.visitorStats": "Estadísticas de visitantes",
    "dashboard.tasks": "Tareas",
    "dashboard.recentActivities": "Actividades recientes",
    "dashboard.topCourses": "Mejores cursos",
    "dashboard.students": "estudiantes",
    "dashboard.thisMonth": "Este mes",
    
    // Users
    "users.title": "Gestión de Usuarios",
    "users.subtitle": "Administrar y organizar usuarios",
    "users.addUser": "Agregar Usuario",
    "users.editUser": "Editar Usuario",
    "users.deleteUser": "Eliminar Usuario",
    "users.fullName": "Nombre Completo",
    "users.emailAddress": "Correo Electrónico",
    "users.userType": "Tipo de Usuario",
    "users.searchPlaceholder": "Buscar por nombre o correo...",
    "users.filterByType": "Filtrar por tipo",
    "users.allTypes": "Todos los tipos",
    "users.learner": "Estudiante",
    "users.instructor": "Instructor",
    "users.admin": "Administrador",
    "users.recruiter": "Reclutador",
    "users.totalUsers": "Total Usuarios",
    "users.admins": "Administradores",
    "users.addSuccess": "¡Usuario agregado exitosamente!",
    "users.updateSuccess": "¡Usuario actualizado exitosamente!",
    "users.deleteSuccess": "¡Usuario eliminado exitosamente!",
    "users.fillAllFields": "Por favor complete todos los campos",
    "users.deleteConfirm": "¿Estás seguro?",
    "users.deleteMessage": "Esta acción no se puede deshacer. Esto eliminará permanentemente la cuenta de usuario.",
    
    // Courses
    "courses.title": "Gestión de Cursos",
    "courses.subtitle": "Crear y administrar cursos",
    "courses.addCourse": "Agregar Curso",
    "courses.editCourse": "Editar Curso",
    "courses.deleteCourse": "Eliminar Curso",
    "courses.viewCourse": "Detalles del Curso",
    "courses.courseName": "Nombre del Curso",
    "courses.instructorName": "Nombre del Instructor",
    "courses.courseType": "Tipo de Curso",
    "courses.description": "Descripción",
    "courses.courseFiles": "Archivos del Curso",
    "courses.searchPlaceholder": "Buscar por nombre o instructor...",
    "courses.filterByType": "Filtrar por tipo",
    "courses.allTypes": "Todos los tipos",
    "courses.totalCourses": "Total Cursos",
    "courses.totalStudents": "Total Estudiantes",
    "courses.totalRevenue": "Ingresos Totales",
    "courses.avgRating": "Calificación Promedio",
    "courses.rating": "Calificación",
    "courses.addSuccess": "¡Curso agregado exitosamente!",
    "courses.updateSuccess": "¡Curso actualizado exitosamente!",
    "courses.deleteSuccess": "¡Curso eliminado exitosamente!",
    "courses.fillRequired": "Por favor complete todos los campos requeridos",
    "courses.deleteConfirm": "¿Estás seguro?",
    "courses.deleteMessage": "Esto eliminará permanentemente el curso y todos los datos asociados.",
    "courses.uploadPrompt": "Haga clic para cargar o arrastre y suelte",
    "courses.uploadHint": "PDF, MP4, PPTX, DOC (máx. 100MB)",
    
    // Enrollments
    "enrollments.title": "Gestión de Inscripciones",
    "enrollments.subtitle": "Rastrear y administrar inscripciones de estudiantes",
    "enrollments.totalEnrollments": "Total Inscripciones",
    "enrollments.inProgress": "En Progreso",
    "enrollments.student": "Estudiante",
    "enrollments.courseName": "Nombre del Curso",
    "enrollments.progress": "Progreso",
    "enrollments.payment": "Pago",
    "enrollments.enrollmentDate": "Fecha de Inscripción",
    "enrollments.completionDate": "Fecha de Finalización",
    "enrollments.paymentStatus": "Estado del Pago",
    "enrollments.courseProgress": "Progreso del Curso",
    "enrollments.finalGrade": "Calificación Final",
    "enrollments.viewDetails": "Ver información completa de inscripción",
    "enrollments.searchPlaceholder": "Buscar inscripciones...",
    "enrollments.filterByStatus": "Filtrar por estado",
    "enrollments.allStatus": "Todos los estados",
    "enrollments.deleteSuccess": "¡Inscripción eliminada exitosamente!",
    "enrollments.exportSuccess": "Exportando datos de inscripciones...",
    
    // Notifications
    "notifications.title": "Notificaciones",
    "notifications.markAllRead": "Marcar todo como leído",
    "notifications.viewAll": "Ver todas las notificaciones",
    "notifications.newUser": "Nuevo usuario registrado",
    "notifications.courseCompleted": "Curso completado",
    "notifications.paymentReceived": "Pago recibido",
    "notifications.newEnrollment": "Nueva inscripción",
    
    // User Menu
    "userMenu.myAccount": "Mi Cuenta",
    "userMenu.profile": "Perfil",
    "userMenu.settings": "Configuración",
    "userMenu.logout": "Cerrar sesión",
    
    // Footer
    "footer.copyright": "© 2026 Formanova",
    
    // Exams
    "exams.title": "Gestión de Exámenes",
    "exams.totalExams": "Total de Exámenes",
    "exams.upcomingExams": "Exámenes Pendientes",
    "exams.activeExams": "Exámenes Activos",
    "exams.passedExams": "Exámenes Aprobados",
    "exams.examTitle": "Título del Examen",
    "exams.course": "Curso",
    "exams.dueDate": "Fecha de Vencimiento",
    "exams.totalQuestions": "Total de Preguntas",
    "exams.attempts": "Intentos",
    "exams.passRate": "Tasa de Aprobación",
    "exams.upcoming": "Pendiente",
    "exams.active": "Activo",
    "exams.searchPlaceholder": "Buscar Exámenes...",
    "exams.sortByType": "Ordenar por Tipo",
    
    // Job Offers
    "jobs.title": "Gestión de Ofertas de Trabajo",
    "jobs.totalJobOffers": "Total de Ofertas de Trabajo",
    "jobs.openPositions": "Puestos Abiertos",
    "jobs.closedPositions": "Puestos Cerrados",
    "jobs.companies": "Empresas",
    "jobs.jobPosition": "Puesto de Trabajo",
    "jobs.company": "Empresa",
    "jobs.postedDate": "Fecha de Publicación",
    "jobs.applicationDeadline": "Fecha Límite de Aplicación",
    "jobs.open": "Abierto",
    "jobs.closed": "Cerrado",
    "jobs.searchPlaceholder": "Buscar Ofertas de Trabajo...",
    
    // Certificates
    "certificates.title": "Gestión de Certificados",
    "certificates.addCertificate": "+ Agregar Certificado",
    "certificates.totalCertificates": "Total de Certificados",
    "certificates.issuedCertificates": "Certificados Emitidos",
    "certificates.verifiedCertificates": "Certificados Verificados",
    "certificates.pendingCertificates": "Certificados Pendientes",
    "certificates.issueDate": "Fecha de Emisión",
    "certificates.verificationCode": "Código de Verificación",
    "certificates.issued": "Emitido",
    "certificates.pending": "Pendiente",
    "certificates.searchPlaceholder": "Buscar Certificados...",
    
    // Payment
    "payment.title": "Gestión de Pagos",
    "payment.totalRevenue": "Ingresos Totales",
    "payment.completedPayments": "Pagos Completados",
    "payment.pendingPayments": "Pagos Pendientes",
    "payment.refunds": "Reembolsos",
    "payment.method": "Método",
    "payment.failed": "Fallido",
    "payment.tasks": "Tareas",
    "payment.showThisMonth": "Mostrar: Este Mes",
    "payment.failedPayments": "Pagos Fallidos",
    "payment.searchPlaceholder": "Buscar Pagos...",
    
    // Statistics
    "stats.title": "Estadísticas",
    "stats.totalUsers": "Total de Usuarios",
    "stats.totalCourses": "Total de Cursos",
    "stats.totalEnrollments": "Total de Inscripciones",
    "stats.certificatesIssued": "Certificados Emitidos",
    "stats.userGrowth": "Crecimiento de Usuarios",
    "stats.monthly": "Mensual",
    "stats.enrollmentsOverview": "Resumen de Inscripciones",
    
    // Settings
    "settings.title": "Configuración",
    "settings.searchPlaceholder": "Buscar Configuración...",
    "settings.general": "General",
    "settings.systemLanguage": "Idioma del Sistema",
    "settings.userSignUp": "Registro de Usuarios",
    "settings.allowSignUp": "Permitir que los nuevos usuarios se registren",
    "settings.adminTheme": "Tema del Panel de Administrador",
    "settings.defaultUserTheme": "Tema Predeterminado para Usuarios",
    "settings.lightTheme": "Tema Claro",
    "settings.darkTheme": "Tema Oscuro",
    "settings.autoTheme": "Automático",
    "settings.timeZone": "Zona Horaria",
    "settings.dateTimeFormat": "Formato de Fecha y Hora",
    "settings.currency": "Moneda",
    "settings.notifications": "Notificaciones",
    "settings.allowNotifications": "Permitir Notificaciones del Sistema",
    "settings.systemUpdateFreq": "Frecuencia de Actualización del Sistema",
    "settings.securityChecksFreq": "Frecuencia de Verificaciones de Seguridad",
    "settings.saveChanges": "Guardar Cambios",
    "settings.weekly": "Semanal",
    "settings.monthly": "Mensual",
    "settings.daily": "Diario",
    
    // Pagination
    "pagination.showing": "Mostrando",
    "pagination.to": "hasta",
    "pagination.of": "de",
    "pagination.entries": "entradas",
  },
  de: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.users": "Benutzer",
    "nav.courses": "Kurse",
    "nav.enrollments": "Anmeldungen",
    "nav.exams": "Prüfungen",
    "nav.jobOffers": "Stellenangebote",
    "nav.certificates": "Zertifikate",
    "nav.payments": "Zahlungen",
    "nav.statistics": "Statistiken",
    "nav.settings": "Einstellungen",
    
    // Common
    "common.search": "Suchen",
    "common.filter": "Filtern",
    "common.export": "Exportieren",
    "common.add": "Hinzufügen",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.close": "Schließen",
    "common.view": "Ansehen",
    "common.actions": "Aktionen",
    "common.status": "Status",
    "common.name": "Name",
    "common.email": "E-Mail",
    "common.password": "Passwort",
    "common.type": "Typ",
    "common.created": "Erstellt",
    "common.price": "Preis",
    "common.free": "Kostenlos",
    "common.active": "Aktiv",
    "common.completed": "Abgeschlossen",
    "common.loading": "Laden",
    "common.success": "Erfolg",
    "common.error": "Fehler",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.totalUsers": "Gesamtbenutzer",
    "dashboard.learners": "Lernende",
    "dashboard.instructors": "Dozenten",
    "dashboard.courses": "Kurse",
    "dashboard.revenue": "Umsatz",
    "dashboard.visitorStats": "Besucherstatistiken",
    "dashboard.tasks": "Aufgaben",
    "dashboard.recentActivities": "Letzte Aktivitäten",
    "dashboard.topCourses": "Top-Kurse",
    "dashboard.students": "Studenten",
    "dashboard.thisMonth": "Dieser Monat",
    
    // Users
    "users.title": "Benutzerverwaltung",
    "users.subtitle": "Benutzer verwalten und organisieren",
    "users.addUser": "Benutzer hinzufügen",
    "users.editUser": "Benutzer bearbeiten",
    "users.deleteUser": "Benutzer löschen",
    "users.fullName": "Vollständiger Name",
    "users.emailAddress": "E-Mail-Adresse",
    "users.userType": "Benutzertyp",
    "users.searchPlaceholder": "Nach Name oder E-Mail suchen...",
    "users.filterByType": "Nach Typ filtern",
    "users.allTypes": "Alle Typen",
    "users.learner": "Lernender",
    "users.instructor": "Dozent",
    "users.admin": "Administrator",
    "users.recruiter": "Recruiter",
    "users.totalUsers": "Gesamtbenutzer",
    "users.admins": "Administratoren",
    "users.addSuccess": "Benutzer erfolgreich hinzugefügt!",
    "users.updateSuccess": "Benutzer erfolgreich aktualisiert!",
    "users.deleteSuccess": "Benutzer erfolgreich gelöscht!",
    "users.fillAllFields": "Bitte füllen Sie alle Felder aus",
    "users.deleteConfirm": "Sind Sie sicher?",
    "users.deleteMessage": "Diese Aktion kann nicht rückgängig gemacht werden. Dies löscht das Benutzerkonto dauerhaft.",
    
    // Courses
    "courses.title": "Kursverwaltung",
    "courses.subtitle": "Kurse erstellen und verwalten",
    "courses.addCourse": "Kurs hinzufügen",
    "courses.editCourse": "Kurs bearbeiten",
    "courses.deleteCourse": "Kurs löschen",
    "courses.viewCourse": "Kursdetails",
    "courses.courseName": "Kursname",
    "courses.instructorName": "Dozentenname",
    "courses.courseType": "Kurstyp",
    "courses.description": "Beschreibung",
    "courses.courseFiles": "Kursdateien",
    "courses.searchPlaceholder": "Nach Name oder Dozent suchen...",
    "courses.filterByType": "Nach Typ filtern",
    "courses.allTypes": "Alle Typen",
    "courses.totalCourses": "Gesamtkurse",
    "courses.totalStudents": "Gesamtstudenten",
    "courses.totalRevenue": "Gesamtumsatz",
    "courses.avgRating": "Durchschn. Bewertung",
    "courses.rating": "Bewertung",
    "courses.addSuccess": "Kurs erfolgreich hinzugefügt!",
    "courses.updateSuccess": "Kurs erfolgreich aktualisiert!",
    "courses.deleteSuccess": "Kurs erfolgreich gelöscht!",
    "courses.fillRequired": "Bitte füllen Sie alle erforderlichen Felder aus",
    "courses.deleteConfirm": "Sind Sie sicher?",
    "courses.deleteMessage": "Dies löscht den Kurs und alle zugehörigen Daten dauerhaft.",
    "courses.uploadPrompt": "Klicken Sie zum Hochladen oder ziehen Sie per Drag & Drop",
    "courses.uploadHint": "PDF, MP4, PPTX, DOC (max. 100MB)",
    
    // Enrollments
    "enrollments.title": "Anmeldungsverwaltung",
    "enrollments.subtitle": "Studentenanmeldungen verfolgen und verwalten",
    "enrollments.totalEnrollments": "Gesamtanmeldungen",
    "enrollments.inProgress": "In Bearbeitung",
    "enrollments.student": "Student",
    "enrollments.courseName": "Kursname",
    "enrollments.progress": "Fortschritt",
    "enrollments.payment": "Zahlung",
    "enrollments.enrollmentDate": "Anmeldedatum",
    "enrollments.completionDate": "Abschlussdatum",
    "enrollments.paymentStatus": "Zahlungsstatus",
    "enrollments.courseProgress": "Kursfortschritt",
    "enrollments.finalGrade": "Endnote",
    "enrollments.viewDetails": "Vollständige Anmeldeinformationen anzeigen",
    "enrollments.searchPlaceholder": "Anmeldungen suchen...",
    "enrollments.filterByStatus": "Nach Status filtern",
    "enrollments.allStatus": "Alle Status",
    "enrollments.deleteSuccess": "Anmeldung erfolgreich gelöscht!",
    "enrollments.exportSuccess": "Anmeldungsdaten werden exportiert...",
    
    // Notifications
    "notifications.title": "Benachrichtigungen",
    "notifications.markAllRead": "Alle als gelesen markieren",
    "notifications.viewAll": "Alle Benachrichtigungen anzeigen",
    "notifications.newUser": "Neuer Benutzer registriert",
    "notifications.courseCompleted": "Kurs abgeschlossen",
    "notifications.paymentReceived": "Zahlung erhalten",
    "notifications.newEnrollment": "Neue Anmeldung",
    
    // User Menu
    "userMenu.myAccount": "Mein Konto",
    "userMenu.profile": "Profil",
    "userMenu.settings": "Einstellungen",
    "userMenu.logout": "Abmelden",
    
    // Footer
    "footer.copyright": "© 2026 Formanova",
    
    // Exams
    "exams.title": "Prüfungskontrolle",
    "exams.totalExams": "Gesamtzahl der Prüfungen",
    "exams.upcomingExams": "Anstehende Prüfungen",
    "exams.activeExams": "Aktive Prüfungen",
    "exams.passedExams": "Bestandene Prüfungen",
    "exams.examTitle": "Prüfungstitel",
    "exams.course": "Kurs",
    "exams.dueDate": "Fälligkeitsdatum",
    "exams.totalQuestions": "Gesamtzahl der Fragen",
    "exams.attempts": "Versuche",
    "exams.passRate": "Bestehensrate",
    "exams.upcoming": "Anstehend",
    "exams.active": "Aktiv",
    "exams.searchPlaceholder": "Prüfungen suchen...",
    "exams.sortByType": "Nach Typ sortieren",
    
    // Job Offers
    "jobs.title": "Stellenangebote verwalten",
    "jobs.totalJobOffers": "Gesamtzahl der Stellenangebote",
    "jobs.openPositions": "Offene Positionen",
    "jobs.closedPositions": "Geschlossene Positionen",
    "jobs.companies": "Unternehmen",
    "jobs.jobPosition": "Stellenbezeichnung",
    "jobs.company": "Unternehmen",
    "jobs.postedDate": "Veröffentlichungsdatum",
    "jobs.applicationDeadline": "Bewerbungsschluss",
    "jobs.open": "Offen",
    "jobs.closed": "Geschlossen",
    "jobs.searchPlaceholder": "Stellenangebote suchen...",
    
    // Certificates
    "certificates.title": "Zertifikate verwalten",
    "certificates.addCertificate": "+ Zertifikat hinzufügen",
    "certificates.totalCertificates": "Gesamtzahl der Zertifikate",
    "certificates.issuedCertificates": "Ausgestellte Zertifikate",
    "certificates.verifiedCertificates": "Überprüfte Zertifikate",
    "certificates.pendingCertificates": "Ausstehende Zertifikate",
    "certificates.issueDate": "Ausstellungsdatum",
    "certificates.verificationCode": "Überprüfungscode",
    "certificates.issued": "Ausgestellt",
    "certificates.pending": "Ausstehend",
    "certificates.searchPlaceholder": "Zertifikate suchen...",
    
    // Payment
    "payment.title": "Zahlungsverwaltung",
    "payment.totalRevenue": "Gesamtumsatz",
    "payment.completedPayments": "Abgeschlossene Zahlungen",
    "payment.pendingPayments": "Ausstehende Zahlungen",
    "payment.refunds": "Rückerstattungen",
    "payment.method": "Methode",
    "payment.failed": "Fehlgeschlagen",
    "payment.tasks": "Aufgaben",
    "payment.showThisMonth": "Anzeigen: Dieser Monat",
    "payment.failedPayments": "Fehlgeschlagene Zahlungen",
    "payment.searchPlaceholder": "Zahlungen suchen...",
    
    // Statistics
    "stats.title": "Statistiken",
    "stats.totalUsers": "Gesamtzahl der Benutzer",
    "stats.totalCourses": "Gesamtzahl der Kurse",
    "stats.totalEnrollments": "Gesamtzahl der Anmeldungen",
    "stats.certificatesIssued": "Ausgestellte Zertifikate",
    "stats.userGrowth": "Benutzerwachstum",
    "stats.monthly": "Monatlich",
    "stats.enrollmentsOverview": "Übersicht der Anmeldungen",
    
    // Settings
    "settings.title": "Einstellungen",
    "settings.searchPlaceholder": "Einstellungen suchen...",
    "settings.general": "Allgemein",
    "settings.systemLanguage": "Systemsprache",
    "settings.userSignUp": "Benutzerregistrierung",
    "settings.allowSignUp": "Neuen Benutzern das Registrieren erlauben",
    "settings.adminTheme": "Admin-Dashboard-Thema",
    "settings.defaultUserTheme": "Standardthema für Benutzer",
    "settings.lightTheme": "Helles Thema",
    "settings.darkTheme": "Dunkles Thema",
    "settings.autoTheme": "Automatisch",
    "settings.timeZone": "Zeitzone",
    "settings.dateTimeFormat": "Datums- und Zeitformat",
    "settings.currency": "Währung",
    "settings.notifications": "Benachrichtigungen",
    "settings.allowNotifications": "Systembenachrichtigungen erlauben",
    "settings.systemUpdateFreq": "Systemaktualisierungsfrquenz",
    "settings.securityChecksFreq": "Sicherheitsprüfungsfrquenz",
    "settings.saveChanges": "Änderungen speichern",
    "settings.weekly": "Wöchentlich",
    "settings.monthly": "Monatlich",
    "settings.daily": "Täglich",
    
    // Pagination
    "pagination.showing": "Anzeigen",
    "pagination.to": "bis",
    "pagination.of": "von",
    "pagination.entries": "Einträge",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    // Update HTML dir attribute for RTL languages
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}